name: moviedb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_segmented_tab_control: ^2.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  galleryimage: ^2.0.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  loading_animation_widget: ^1.2.1
  page_animation_transition: ^1.0.0
  percent_indicator: ^4.0.1
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "icons"
  ios: true
  image_path: "lib/Assets/cinema.jpeg"
flutter:
  uses-material-design: true
  assets:
    - lib/Assets/
